# Python Review

Goals:
- Recall basic Python vocabulary
- practice markdown

## Libraries and Packages

**library**: A collection of code that we can use to perform specific tasks in our programs.

**NumPy**: 
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optiomized for speed and memory usage

Let's import NumPy with **standard abbreviation**

In [1]:
import numpy as np

## Variables

**variable***: a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable `a`
a = np.array([[1, 1, 2] , [3, 5, 8]])

In [3]:
# Run cell with the variable name to show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


# Objects

**object** (informally speaking) is a bundle of *properties* and **actions** about something specific.

Example:

Object: Data frame

**Properties**: Number rows, names of the columns, date created

**Actions**: selecting a specific row, adding a new column

A **variable** is the name we give a specific object, and the same object can be reference by different variables.

In practice, we can often use variable and object interchangeably.

# Types

Every object in Python has a **type**, the type tells us what kind of object it is.
We can also call the type of an object, the **class** of an object and they both mean whta kind of object we have

Type tells us what kind of object it is.
- The type of an object can also be the class of an object. The **class and type both mean what kind of object do we have**


In [8]:
print(a)
# you can see the type/ class of a variable/ object by using `type`
type(a)
# returns numpy.ndarray

[[1 1 2]
 [3 5 8]]


numpy.ndarray

#### **numpy.ndarray** is the core object/ datatype in the NumPy package. 
#### We can check the type of an entry in the array by **indexing**

In [9]:
# first row, first column
print(a[0,0])

# Check the type on an entry on the array by indexing
type(a[0,0])

1


numpy.int64

Notice the `type(a[0,0])` is `numpy.int64` and not just the standard Python integer type int. The NumPy type numpy.int64 is telling us 1 is an integer stored as a 64-bit number. 

- NumPy has its own data types to deal with numbers depending on memory storage and floating point precision, click here to know see all the types.

In [16]:
print(a)
#How would you access the value 5 in the array a?
a[1,1]

[[1 1 2]
 [3 5 8]]


5

## Functions

`print` was our first example of a Python **function**

Functions take in a set of ***arguments***, separated by commas, and use those arguments to create an output.
- argument = parameter

We can ask information about a function by `?print`

There are several built-in funcions in Python, most of them are for interacting with the Python basic **data types** such as 
- `int` (integers), 
- `float` (decimal numbers), 
- `str` (strings), 
- `bool` (boolean values)

A parameter is a variable in the function definition that accepts an argument passed to the function. It is a placeholder in the function that will receive the value of an argument when the function is called.

In [17]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**

A function has two types of arguments:

- **non-optional argument** arguments *you* need to specify for the function to do something.

- **optional argument** arguments that are pre-filled with a defualt value by the function. You can override them.
Optional arguments appear inside the parenthesis in the form `optional_argument=default_value`

In [18]:
print('changing the default end argument', end=' :)')

changing the default end argument :)

## Attribytes & methods

An object in Python has attributes and methods.

- **Attribute**: A property of an object, some piece of information on it.
- **Method**: A procedure associated with the object, an action where the main ingredient is the object.

## Check-in:

Fish Attributes: 
- length
- color
- species

Methods: 
- die() 
- bite() 
- swim()

## Example

Attributes for `numpy.arrays`

We can access a variable's attributes and methods by adding a period, `.` at the end of the variable's name.

`variable.method()` or `variable.attribute`

In [21]:
a.shape

(2, 3)

In [23]:
type(a.shape)

tuple

In [27]:
# METHODS EXAMPLES
print(a)
# min() returns the minimum value along a specific axis
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

## Check-in

We can also call the `min` method without any parameter:
- optional parameter

In [28]:
a.min()

1

Remember methods are functions associated with an object.

In [29]:
type(a.min)

builtin_function_or_method

## Exercise
1. Read the `print` function help. 
What is the **type** of the argument `sep`? Is this an optional or non-optional argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variables to print `77%99%77` by changing the value of one of the optional arguments in `print`.

In [30]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

1. Sep is used for string(spaces, letters, underscores). Optional bc it is not always necessary


In [36]:
# 2 
# Integer/ Number
x = 77

#String
y = '99' 
print(x,y)

# 3 
print(x,y,x, sep='%')

77 99
77%99%77


In [ ]:
3. 